### PR TITLE
Set wallet parameters from Agent

### PR DESCRIPTION
**Pull request by ianco**
This code is w.i.p. however PR is created for code review and comments.

I have added parameters to the wallet to allow the Agents to set wallet type, config and credentials.  There are corresponding changes to TheOrgBook and Permitify.

Questions:

- There is one location in the code (commented as "TODO") were the wallet is opened internally, this still needs to be updated
- Not sure why von_agent is closing/opening (and looks like deleting/re-creating?) the wallet internally
- Not sure if config and credentials validation is going to work inside von_agent, the structure will depend on the wallet type, and I don't think we want wallet changes to require von_agent changes

### CODE REVIEW

**Review by sklump — COMMENTED** [review]
As far as configuration validation is concerned on the wallet, it's not checking correctness of credentials or anything, it's just making sure that the wallet configuration dict contains only settings that are usable - i.e., fail fast on a setting that is clearly wrong.

**Review by sklump — COMMENTED** [review]
re: agents.py Issuer wallet re-open at line 816

This check occurs only if a claim definition is already present in a wallet before it is on the ledger -- this means that the ledger has been wiped out and the wallet is for use with a dead ledger. It's hopeless - as it stands right now, the right thing to do is to remove and re-open the wallet, so I think it ought to take the full parameter set. The alternative is a 'remove everything from this wallet' command right on the wallet itself, but at present, the default wallet type does not offer such a mechanism.

As for wallet.type, I'd prefer to call it `xtype` (1) to align with indy-sdk and (2) to avoid using a reserved word. It's a tiny tiny quibble only. I am more than willing to do the grunt work to tweak it on integration.

**Comment by ianco** [comment]
Thanks for the feedback!

I'll fix the wallet.type (rename to xtype), and I'll see if I can fix the wallet create/open as well (taking all parameters).

**Comment by ianco** [comment]
Closed for now, will re-base and open a new PR if any further changes are needed

**Pull request closed without merging**
